-- 1. Retrieve the names and locations of restaurants with a rating of 4.5 or higher.
SELECT r.name, r.city, r.rating
FROM restaurants r
WHERE rating >= 4.5;

-- 2. Find the total number of orders placed by each customer.
SELECT c.firstname, c.lastname, count(o.orderid) AS orderplacedbycustomer
FROM customers c
LEFT JOIN orders o ON c.customerid = o.customerid
GROUP BY c.firstname, c.lastname;

-- 3. List all restaurants offering "Italian" cuisine in "Mumbai".
SELECT *
FROM Restaurants
WHERE CuisineType = 'Italian' AND City = 'Mumbai';

-- 4. Calculate the total revenue generated by each restaurant from completed orders.
SELECT r.name, sum(o.orderamount) AS totalrevenue
FROM restaurants r
JOIN orders o on r.restaurantid = o.restaurantid
WHERE orderstatus = 'Delivered'
GROUP BY r.name;

-- 5. Retrieve the most recent order placed by each customer.
SELECT o.*
FROM Orders o
JOIN (
    SELECT CustomerID, MAX(OrderDate) AS MaxDate
    FROM Orders
    GROUP BY CustomerID
) latest
ON o.CustomerID = latest.CustomerID AND o.OrderDate = latest.MaxDate;

-- 6. List customers who have not placed any orders yet.
SELECT c.CustomerID, c.FirstName, c.LastName, c.City
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.OrderID IS NULL;

-- 7. Identify the most reviewed restaurants.
SELECT r.RestaurantID, r.Name, COUNT(rev.ReviewID) AS ReviewCount
FROM Restaurants r
JOIN Reviews rev ON r.RestaurantID = rev.RestaurantID
GROUP BY r.RestaurantID, r.Name
ORDER BY ReviewCount DESC;

-- 8. Find the most preferred payment method.
SELECT PaymentMethod, COUNT(*) AS MethodCount
FROM Payments
GROUP BY PaymentMethod
ORDER BY MethodCount DESC
LIMIT 1;

-- 9. List the top 5 restaurants by total revenue.
SELECT r.RestaurantID, r.Name, SUM(o.OrderAmount) AS TotalRevenue
FROM Restaurants r
JOIN Orders o ON r.RestaurantID = o.RestaurantID
WHERE o.OrderStatus = 'Delivered'
GROUP BY r.RestaurantID, r.Name
ORDER BY TotalRevenue DESC
LIMIT 5;

-- 10. Show the details of all cancelled orders along with the customer's and restaurant's names.
SELECT 
    o.OrderID,
    c.FirstName,
    c.LastName,
    r.Name AS RestaurantName,
    o.OrderDate,
    o.OrderAmount,
    o.OrderStatus
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN Restaurants r ON o.RestaurantID = r.RestaurantID
WHERE o.OrderStatus = 'Cancelled';







